[project]
name = "qis101"
version = "0.1.0"
description = "Foundations of Quantum Information Science (QIS101)"
readme = "README.md"

requires-python = ">=3.12,<3.13"

dependencies = [
    "apptools",
    "beautifulsoup4",
    "black",
    "configobj",
    "datasets",
    "ipympl",
    "ipython",
    "jax[cpu]",
    "joblib",
    "jupyter",
    "matplotlib",
    "mayavi==4.8.3",
    "networkx",
    "numba",
    "numexpr",
    "numpy",
    "pandas",
    "pennylane",
    "pip",
    "pulp",
    "pyface",
    "pygame",
    "pyqt6",
    "pyside6",
    "pyside6-addons",
    "qiskit-aer",
    "qiskit-algorithms",
    "qiskit-experiments",
    "qiskit-ibm-catalog",
    "qiskit-ibm-runtime",
    "qiskit-machine-learning",
    "qiskit-nature",
    "qiskit-optimization",
    "qiskit[all,visualization]",
    "ray[data]",
    "ruff",
    "scikit-learn",
    "scipy",
    "seaborn",
    "selenium",
    "setuptools",
    "sympy",
    "torch",
    "tqdm",
    "traitsui",
    "transformers",
    "vtk>=9.4,<9.5",
    "webdriver-manager",
    "wheel",    
    "torchvision",
    "torchaudio",
    "cupy-cuda12x",
]

[tool.uv]
# mayavi is built without build isolation so it can see the right numpy, etc.
no-build-isolation-package = ["mayavi"]

# Force resolver to include Windows compatibility
required-environments = [
  "sys_platform == 'win32' and platform_machine == 'AMD64'"
]

[[tool.uv.dependency-metadata]]
name = "mayavi"
version = "4.8.3"
requires-dist = ["numpy"]

[tool.ruff]
extend-include = ["*.ipynb"]
lint.extend-select = ["I", "C4", "ISC", "SIM", "TCH"]
lint.ignore = []
show-fixes = true
target-version = "py314"

[[tool.uv.index]]
name = "pytorch-cu124"
url = "https://download.pytorch.org/whl/cu124"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu124" }
torchvision = { index = "pytorch-cu124" }
torchaudio = { index = "pytorch-cu124" }
